---
- name: Install prerequisite tools for docker
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add an Apt signing key for docker
  become: yes
  apt_key:
    id: 0EBFCD88
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Apt-Source
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: 100-ubnt-docker

- name: Install docker
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Copy Docker-Container-Startup-Script for Unifi-Controller
  become: yes
  template:
    src: 'start-unifi-docker.sh.j2'
    dest: /home/ffbsee/start-unifi-docker.sh
    owner: ffbsee
    group: ffbsee
    mode: u=rwxr,g=rx,o=x
